language: objective-c
osx_image: xcode8
script:
- xcodebuild test -project materialDesign.xcodeproj -scheme materialDesign -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty -c
- xcodebuild -project materialDesign.xcodeproj -scheme materialDesign-watchOS -destination 'name=Apple Watch - 42mm' | xcpretty -c
before_deploy:
  - carthage build --no-skip-current
  - carthage archive materialDesign
deploy:
  provider: releases
  api_key:
    secure: cas9AI0zCDIumfTKk79sazU6PLuVXICET6eIjqivntG1Qs1g9yvmsI3JbBMLPyZqDl0w+uDHhki7cBeO3tDXJ8cxIErj8xYwtX4TMnA916QWqo7DVkGjkqAxosWWBGBgx6VbcSw0WSnPYrlo41c5yKssuDal+CZjoTeadJqB8Rg=
  file: materialDesign.framework.zip
  skip_cleanup: true
  on:
    tags: true
    repo: thii/materialDesign.swift
